### PR TITLE
#19/readme and fixes

### LINKED ISSUE #19: Write readme
# Overview

We need comprehensive readme because for FD readme is a library documentation.

# Tasks

- [ ] follow readme structure from https://github.com/frictionlessdata/jsontableschema-py (sections features/getting started/etc)
- [ ] write readme

### PR DESCRIPTION
**Pull request by dumyan**
@roll

please review the README work and also the other fixes regarding `validate.js` and `resource.js`.

fixes #19

### CODE REVIEW

File: test/datapackage.js [hunk 1]
```diff
@@ -180,4 +180,36 @@ describe('Datapackage', () => {
       assert(_.isEqual(data, expectedData), 'Wrong data loaded')
     })
   })
+
+  describe('README', () => {
+    const testDatapackage = 'http://bit.do/datapackage-json'
```
Comment (dumyan) [inline test/datapackage.js]: This link currently is pointing to the `data/dp3-inline/datapackage.json` github repo from keitaro. It would be good if we upload this on FD domain.

I think it is best if the users have some copy-paste examples to try out, that's why I opted for outside URL for the README tests.

File: src/validate.js [hunk 2]
```diff
@@ -18,18 +18,22 @@ export default function validate(descriptor
   const remoteString = remoteProfiles.toString()
 
   if (PROFILES_CACHED[remoteString]) {
-    return new Promise(resolve => {
+    return new Promise((resolve, reject) => {
       PROFILES_CACHED[remoteString].then(profiles => {
         resolve(profiles.validate(descriptor, profile))
+      }).catch(err => {
+        reject(err)
```
Comment (dumyan) [inline src/validate.js]: We need this rejections to happen in the scenario when `remote` profiles are being used but connection can't be made.

File: src/resource.js [hunk 3]
```diff
@@ -36,21 +36,22 @@ export default class Resource {
...
     }
 
-    if (_.includes(this.REMOTE_PROTOCOLS, protocol)) {
-      return 'remote'
+    const source = this.descriptor[this._sourceKey]
+    if (typeof source === 'string') {
+      const protocol = url.parse(source).protocol
+      if (_.includes(this.REMOTE_PROTOCOLS, protocol)) {
+        return 'remote'
+      }
```
Comment (dumyan) [inline src/resource.js]: This is needed because url.parse throws an error if the `source` argument is not a string. Our tests covered only inline data that is string so we missed this one.

File: data/dp3-inline-data/datapackage.json [hunk 4]
```diff
@@ -0,0 +1,30 @@
...
+          },
+          {
+            "name": "name",
+            "type": "string"
+          }
+        ]
+      }
+    }
+  ]
+}
```
Comment (dumyan) [inline data/dp3-inline-data/datapackage.json]: Maybe think of some not random data for the README tests?
